### ISSUE TITLE
Incidencias críticas.

### ISSUE THREAD

**Issue by pabloalvrz** [Arquisoft/InciDashboard_e2a#7]
Determinar que tipo de incidencias son críticas y por lo tanto necesitamos controlar sus umbrales o simplemente el mero hecho de la aparicion de la incidencia ya es crítico. Ejemplo:
La temperatura la consideraremos critica cuando supere los 50º o sea menor a xº
El fuego en sí es crítico

**Comment by PablooD9** [comment]
Los administradores tendrán la opción de configurar estos valores.

**Comment by ferpobe** [comment]
Esto no creo que haya que manejarlo. Quiero decir sera el operador el que decida "manualmente" porque si no apareceria otro microservicio que gestionara estos valores y se lo pasara ya decidido al operador.
Por ejemplo: incidencia con campo fuego:true o algo asi seria una incidencia critica y el operador ya lo sabria porque ya se decidio automaticamente antes.
Porque si hacemos esto habri que configurar el dashboard cada vez que llegara un campo nuevo.
tendria mas sentido que esto se gestionara en un microservicio intermedio.
Creo yo.

**Comment by PablooD9** [comment]
Ya han sido, más o menos, integradas en la aplicación.
